# Análise Exploratória - Minas Gerais (MG)

Responsável: Leonardo Pires

Base utilizada:
- detalhe_votacao_secao_2022_MG.csv

In [5]:
# Importação da biblioteca utilizada para análise de dados
import pandas as pd

# Leitura da base de votação de Minas Gerais
df = pd.read_csv(
    "../dados/detalhe_votacao_secao_2022_MG.csv",
    encoding="latin1",
    sep=";"
)

# Verificação da quantidade de linhas e colunas da base
df.shape

(199924, 37)

In [4]:
list(df.columns)

['DT_GERACAO',
 'HH_GERACAO',
 'ANO_ELEICAO',
 'CD_TIPO_ELEICAO',
 'NM_TIPO_ELEICAO',
 'NR_TURNO',
 'CD_ELEICAO',
 'DS_ELEICAO',
 'DT_ELEICAO',
 'TP_ABRANGENCIA',
 'SG_UF',
 'SG_UE',
 'NM_UE',
 'CD_MUNICIPIO',
 'NM_MUNICIPIO',
 'NR_ZONA',
 'NR_SECAO',
 'CD_CARGO',
 'DS_CARGO',
 'QT_APTOS',
 'QT_COMPARECIMENTO',
 'QT_ABSTENCOES',
 'QT_VOTOS_NOMINAIS',
 'QT_VOTOS_BRANCOS',
 'QT_VOTOS_NULOS',
 'QT_VOTOS_LEGENDA',
 'QT_VOTOS_ANULADOS_APU_SEP',
 'NR_LOCAL_VOTACAO',
 'NM_LOCAL_VOTACAO',
 'DS_LOCAL_VOTACAO_ENDERECO',
 'DT_RECEBIMENTO_BU_HOR_TSE',
 'DT_PRIM_TOT_PARCIAL_HOR_TSE',
 'DS_ORIGEM_VOTO',
 'ST_SECAO_INSTALADA',
 'ST_SECAO_ANULADA',
 'CD_MODELO_URNA',
 'DS_MODELO_URNA']

In [7]:
# Visualização das primeiras linhas da base
# Objetivo: entender o que cada registro representa
df.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,DS_LOCAL_VOTACAO_ENDERECO,DT_RECEBIMENTO_BU_HOR_TSE,DT_PRIM_TOT_PARCIAL_HOR_TSE,DS_ORIGEM_VOTO,ST_SECAO_INSTALADA,ST_SECAO_ANULADA,CD_MODELO_URNA,DS_MODELO_URNA
0,15/02/2024,15:56:11,2022,2,Eleição Ordinária,1,546,Eleições Gerais Estaduais 2022,02/10/2022,E,...,1058,ESCOLA MUNICIPAL SANTANA DO RIO PRETO,POVOADO SANTANA DO RIO PRETO,02/10/2022 20:50:41,02/10/2022 20:50:57,Urna Eletrônica,Sim,Não,2020,UE 2020
1,15/02/2024,15:56:11,2022,2,Eleição Ordinária,1,546,Eleições Gerais Estaduais 2022,02/10/2022,E,...,1058,ESCOLA MUNICIPAL SANTANA DO RIO PRETO,POVOADO SANTANA DO RIO PRETO,02/10/2022 20:50:41,02/10/2022 20:50:57,Urna Eletrônica,Sim,Não,2020,UE 2020
2,15/02/2024,15:56:11,2022,2,Eleição Ordinária,1,546,Eleições Gerais Estaduais 2022,02/10/2022,E,...,1058,ESCOLA MUNICIPAL SANTANA DO RIO PRETO,POVOADO SANTANA DO RIO PRETO,02/10/2022 20:50:41,02/10/2022 20:50:57,Urna Eletrônica,Sim,Não,2020,UE 2020
3,15/02/2024,15:56:11,2022,2,Eleição Ordinária,1,546,Eleições Gerais Estaduais 2022,02/10/2022,E,...,1058,ESCOLA MUNICIPAL SANTANA DO RIO PRETO,POVOADO SANTANA DO RIO PRETO,02/10/2022 20:50:41,02/10/2022 20:50:57,Urna Eletrônica,Sim,Não,2020,UE 2020
4,15/02/2024,15:56:11,2022,2,Eleição Ordinária,1,546,Eleições Gerais Estaduais 2022,02/10/2022,E,...,1112,ESCOLA MUNICIPAL PROFESSORA HELENA EUSTÁQUIA D...,"RUA SANTA EFIGÊNIA, 321",02/10/2022 20:29:34,02/10/2022 20:30:41,Urna Eletrônica,Sim,Não,2020,UE 2020

### Observação inicial
A base está organizada por seção eleitoral.
Cada linha representa uma seção eleitoral específica, contendo informações sobre comparecimento, abstenções e votos.

## Estrutura da base de dados

Nesta etapa foi realizada uma inspeção inicial da estrutura da base,
com o objetivo de identificar quantidade de registros, tipos de dados,
presença de valores nulos e uso de memória.

In [ ]:
# Verificação da estrutura da base de dados
# Objetivo: identificar quantidade de registros, tipos de dados,
# valores não nulos e consumo de memória

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 199924 entries, 0 to 199923
Data columns (total 37 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   DT_GERACAO                   199924 non-null  str
 1   HH_GERACAO                   199924 non-null  str
 2   ANO_ELEICAO                  199924 non-null  int64
 3   CD_TIPO_ELEICAO              199924 non-null  int64
 4   NM_TIPO_ELEICAO              199924 non-null  str
 5   NR_TURNO                     199924 non-null  int64
 6   CD_ELEICAO                   199924 non-null  int64
 7   DS_ELEICAO                   199924 non-null  str
 8   DT_ELEICAO                   199924 non-null  str
 9   TP_ABRANGENCIA               199924 non-null  str
 10  SG_UF                        199924 non-null  str
 11  SG_UE                        199924 non-null  str
 12  NM_UE                        199924 non-null  str
 13  CD_MUNICIPIO                 199924 non-null  int64
 14  NM_MUNICIPIO                 199924 non-null  str
 15  NR_ZONA                      199924 non-null  int64
 16  NR_SECAO                     199924 non-null  int64
 17  CD_CARGO                     199924 non-null  int64
 18  DS_CARGO                     199924 non-null  str
 19  QT_APTOS                     199924 non-null  int64
 20  QT_COMPARECIMENTO            199924 non-null  int64
 21  QT_ABSTENCOES                199924 non-null  int64
 22  QT_VOTOS_NOMINAIS            199924 non-null  int64
 23  QT_VOTOS_BRANCOS             199924 non-null  int64
 24  QT_VOTOS_NULOS               199924 non-null  int64
 25  QT_VOTOS_LEGENDA             199924 non-null  int64
 26  QT_VOTOS_ANULADOS_APU_SEP    199924 non-null  int64
 27  NR_LOCAL_VOTACAO             199924 non-null  int64
 28  NM_LOCAL_VOTACAO             199924 non-null  str
 29  DS_LOCAL_VOTACAO_ENDERECO    199924 non-null  str
 30  DT_RECEBIMENTO_BU_HOR_TSE    199924 non-null  str
 31  DT_PRIM_TOT_PARCIAL_HOR_TSE  199924 non-null  str
 32  DS_ORIGEM_VOTO               199924 non-null  str
 33  ST_SECAO_INSTALADA           199924 non-null  str
 34  ST_SECAO_ANULADA             199924 non-null  str
 35  CD_MODELO_URNA               199924 non-null  int64
 36  DS_MODELO_URNA               199924 non-null  str
dtypes: int64(18), str(19)
memory usage: 56.4 MB

### Observações iniciais

A base referente ao estado de Minas Gerais possui 199.924 registros e 37 colunas.

Durante a inspeção inicial foi observado que a base contém variáveis numéricas e categóricas em quantidade suficiente para a realização da análise exploratória.

O consumo de memória da base é de aproximadamente 56,4 MB.

## Verificação de valores ausentes

Nesta etapa será analisada a presença de valores ausentes em cada coluna da base.

In [33]:
# Verificação da quantidade de valores ausentes por coluna
# Objetivo: identificar possíveis problemas de preenchimento
# que necessitem tratamento na etapa de limpeza dos dados.

df.isna().sum()

DT_GERACAO                     0
HH_GERACAO                     0
ANO_ELEICAO                    0
CD_TIPO_ELEICAO                0
NM_TIPO_ELEICAO                0
NR_TURNO                       0
CD_ELEICAO                     0
DS_ELEICAO                     0
DT_ELEICAO                     0
TP_ABRANGENCIA                 0
SG_UF                          0
SG_UE                          0
NM_UE                          0
CD_MUNICIPIO                   0
NM_MUNICIPIO                   0
NR_ZONA                        0
NR_SECAO                       0
CD_CARGO                       0
DS_CARGO                       0
QT_APTOS                       0
QT_COMPARECIMENTO              0
QT_ABSTENCOES                  0
QT_VOTOS_NOMINAIS              0
QT_VOTOS_BRANCOS               0
QT_VOTOS_NULOS                 0
QT_VOTOS_LEGENDA               0
QT_VOTOS_ANULADOS_APU_SEP      0
NR_LOCAL_VOTACAO               0
NM_LOCAL_VOTACAO               0
DS_LOCAL_VOTACAO_ENDERECO      0
DT_RECEBIMENTO_BU_HOR_TSE      0
DT_PRIM_TOT_PARCIAL_HOR_TSE    0
DS_ORIGEM_VOTO                 0
ST_SECAO_INSTALADA             0
ST_SECAO_ANULADA               0
CD_MODELO_URNA                 0
DS_MODELO_URNA                 0
dtype: int64

### Análise dos valores ausentes

Foi realizada a verificação da presença de valores ausentes na base de dados utilizando o método `isna().sum()`.

O resultado indicou que nenhuma das 37 colunas apresenta valores ausentes.

Dessa forma, não será necessário realizar tratamento de dados faltantes nesta etapa da análise.

In [20]:
# Verificação da quantidade de registros duplicados
# Objetivo: identificar linhas repetidas que possam
# comprometer as análises estatísticas.

df.duplicated().sum()

np.int64(0)

### Observações
O resultado obtido foi igual a 0, indicando que não existem registros duplicados na base de dados analisada.
Dessa forma, não foi necessário realizar qualquer tratamento relacionado à remoção de duplicidades.

## Análise das categorias

Nesta etapa será realizada uma análise inicial das variáveis categóricas da base, com o objetivo de identificar os valores presentes e possíveis inconsistências.

In [23]:
# Verificação das categorias presentes na coluna de cargos

df["DS_CARGO"].value_counts()

DS_CARGO
Senador              49981
Deputado Federal     49981
Governador           49981
Deputado Estadual    49981
Name: count, dtype: int64

### Observações

Foram identificados quatro cargos na base de dados:

- Governador;
- Senador;
- Deputado Federal;
- Deputado Estadual.

Cada cargo apresenta exatamente 49.981 registros.

Não foram observadas inconsistências de escrita, duplicidades de categorias ou valores inesperados para esta variável.

## Verificação da distribuição dos municípios

Nesta etapa será realizada uma inspeção da variável `NM_MUNICIPIO`,
com o objetivo de identificar possíveis inconsistências de categorização.

In [28]:
# Quantidade de municípios distintos presentes na base

df["NM_MUNICIPIO"].nunique()

853

### Observações

Foram identificados quatro cargos distintos na base de dados:

- Governador;
- Senador;
- Deputado Federal;
- Deputado Estadual.

Cada cargo apresenta exatamente 49.981 registros.

Não foram observadas inconsistências de preenchimento ou variações de nomenclatura nesta variável.

Dessa forma, a coluna `DS_CARGO` apresenta consistência categórica para os registros analisados.

## Estatísticas descritivas das variáveis numéricas

Nesta etapa será realizada uma análise inicial das variáveis numéricas da base, com o objetivo de identificar possíveis valores inconsistentes e compreender a distribuição dos dados.

In [37]:
# Estatísticas descritivas das variáveis numéricas

df[
    [
        "QT_APTOS",
        "QT_COMPARECIMENTO",
        "QT_ABSTENCOES",
        "QT_VOTOS_NOMINAIS",
        "QT_VOTOS_BRANCOS",
        "QT_VOTOS_NULOS"
    ]
].describe()

,QT_APTOS,QT_COMPARECIMENTO,QT_ABSTENCOES,QT_VOTOS_NOMINAIS,QT_VOTOS_BRANCOS,QT_VOTOS_NULOS
count,199924.000000,199924.000000,199924.000000,199924.000000,199924.000000,199924.000000
mean,325.543967,252.969949,72.574018,211.565055,17.644685,18.039010
std,71.934579,60.666918,24.374527,51.320289,10.280256,10.573816
min,22.000000,15.000000,1.000000,9.000000,0.000000,0.000000
25%,286.000000,217.000000,56.000000,181.000000,10.000000,10.000000
50%,335.000000,260.000000,71.000000,215.000000,16.000000,17.000000
75%,372.000000,292.000000,88.000000,244.000000,24.000000,25.000000
max,572.000000,461.000000,244.000000,444.000000,83.000000,88.000000

### Observações

A análise descritiva das principais variáveis numéricas indicou que os valores observados são compatíveis com a realidade das seções eleitorais.

Não foram identificados valores negativos ou inconsistências evidentes nas variáveis analisadas.

As quantidades de eleitores aptos, comparecimento, abstenções e votos apresentaram distribuições compatíveis com o contexto eleitoral da base estudada.